dbt_llyod:
  target: dbt_dataset

  outputs:
    bronze:
      dataset: bronze
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}" 
      location: US
      method: service-account
      priority: interactive
      project: int-dev-001
      threads: 1
      type: bigquery

    silver:
      dataset: silver  
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}" 
      location: US
      method: service-account
      priority: interactive
      project: int-dev-001
      threads: 1
      type: bigquery
     

    gold:
      dataset: gold
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}" 
      location: US
      method: service-account
      priority: interactive
      project: int-dev-001
      threads: 1
      type: bigquery
      
      
    dbt_dataset:
      dataset: dbt_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}" 
      location: US
      method: service-account
      priority: interactive
      project: int-dev-001
      threads: 1
      type: bigquery
      

